
# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

version: 2

# Personal info
name: Cayman 符基文 
title: 信息技术经理 / IT Manager
phone: +86 131 1198 6898
email: iam@kman.vip
website: https://kman.homes

# Social links
#twitter_username: sproogen
#github_username:  fujiwen
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: jameswgrant
linkedin_username: caymanfu
# pinterest_username:
# youtube_username:
additional_links:
- title: Gallery相册
  icon: fas fa-images
  url: https://photo.kman.xyz
- title: Blog博客
  icon: fas fa-blog
  url: https://kman.homes

# About Section
about_title: 自我介绍
about_profile_image: images/profile.png
about_content: |

  *“你不像是一个IT”* 常听同事们对我说。
  
  您好，我是Cayman符基文，一名有着丰富的创造力、想像力、协调能力以及酒店筹开经验的<mark>IT经理</mark>。 
  
  在接近<mark>10年</mark>的酒店职业生涯中，我服务过<mark>4家</mark>不同的国际酒店品牌，独立负责其中3家酒店从0到1的筹开，房量超过<mark>1900间</mark>。
  
  我目前做为 <mark>信息技术方案经理</mark> 服务于 <mark>海口索菲特大酒店</mark>，负责酒店IT部门并全力支持着酒店运营业务。
  
  同时，做为雅高集团华南区域<mark>IT CLuster Leader</mark>，也为区域内16家酒店（超过5000间客房）提供包括新ITM招聘，入职培训，项目实施交付及业务支持等。

  10年的酒店服务生涯，我听过最多的的评价是，<mark>你不像是一个IT</mark>。我深以为然，也把这个评价当做是褒奖。
  
  我认为同事们的评价和我以不同的角色来参与酒店的运营是密切联系。
  
  所以我不仅仅是IT，我也是：

   -  [IT CLuster Leader South CHINA](https://github.com/sproogen/itsgoingto.be)
   -  [ DJ ](https://github.com/sproogen/itsgoingto.be)
   -  [市场活动策划、协调、执行人](https://github.com/sproogen/itsgoingto.be)
   -  [内部活动主持人](https://github.com/sproogen/itsgoingto.be)
   -  [视频剪辑师](https://github.com/sproogen/itsgoingto.be)
   -  [品牌服务文化培训师](https://github.com/sproogen/itsgoingto.be)


 
    ![Trees](https://minio.kman.xyz/picgo/202404101752977.jpg "Team")

content:
  - title: 项目 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Social Media Hub
        link: vlink.cc/sofitel_haikou
        # link_text: Project Website
        additional_links:
          - title:  vlink.cc/sofitel_haikou
            icon: fas fa-globe
            url: vlink.cc/sofitel_haikou
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
           “Social Media Hub社交媒体中心” 是一个集中的平台，可以汇聚和管理来自多个来源的社交媒体内容，应用于各种场景。
        description: | # this will include new lines to allow paragraphs
         最近，我发起并创建了 <mark>Social Media Hub</mark> 这个特别的项目 - 它是一个单链接网页，它可以在一个页面里分享多个活动链接，这样你的关注者、宾客就可以在一个网页中找到他们所需要的一切。
         
         我们可以将它添加到社交媒体平台（如抖音和小红书）的个人资料链接中，甚至可以将其显示为QR码，投放到客房内的电视上，以引导线下的宾客与线上活动连接起来。
         
         我负责了这个项目内的全部的编码及布局设计以及URL地址的转换的工作，如果你刚也感兴趣，欢迎联系我呀。


          
  - title: 工作经历
    layout: list
    content:
      - layout: left
        border: weak
        title: 海口索菲特大酒店
        sub_title: 信息技术方案经理 ｜ 209 Rooms
        caption: March 2020 - Present
        description: |
          工作表现：
            
            - 独立完成酒店筹开期所有的相关的工作任务，包含但不限于：<mark>基础设施规划和建设</mark>  / <mark>系统选型和集成</mark>  / <mark>数据管理和安全</mark>  / <mark>设备采购和安装</mark>  / <mark>培训和支持</mark> / <mark>项目管理和协调 </mark> / <mark>预算编制及优化</mark> 
            - 引入新方案优化客房部服务业务流程中的痛点，以解决外包人员排班、房态更新、迷你吧抛帐等业务繁琐的手工操作流程，专注于宾客服务体验。据统计，新方案将每年为酒店优化出至少<mark>3000小时</mark>工作时间。
            - 引入宾客质量跟踪模块，量化酒店工程、客房、前厅、餐饮服务过程中的数据，形成周期报表，以提供给到部门及管理层决策及参考。
            - 搭建酒店内部通讯平台，审批流程数字化，满足酒店内部的沟通和协作需求。
            - 开发和集成chatgpt功能插件到平台并提供给全员使用，MKT、餐饮、宾客服务部门都使用此功能进行宾客反馈评论。
            - 持续对酒店业务系统及服务进行更新和迭代，优化业务成本支出. - PMS系统按预期进行更新和迭代将为酒店在5年周期内成本下降<mark>20万元</mark>，餐饮系统5年期成本下降<mark>5万元</mark>。
            - 2021年通过"雅高大中华区品牌文化认证",成为酒店品牌服务文化培训讲师。 

          团队协作：

            - 参与酒店发起的市场活动，包含前期提供策划和创意，活动现场环境的氛围音乐的选定，现场的协调及执行 -  多为现场支持角色，确保活动按计划顺利进行。
            - 担任<mark>DJ</mark> / <mark>主持人</mark> 角色，配合酒店内外部活动，如酒店年会、餐厅圣诞节&跨年活动
          

          嘉奖&认可：

            - 年度优秀经理 Manager of the year 2023
            - 年度优秀IT领导人 Excelent IT Manager ACCOR TEACH GREATER CHINA  2023
            - 年度部门业务创新奖 Business Innovation Award In Department 2023
            - 品牌服务文化讲师认证 Brand Service Culture Certifacation Accor Greater CHINA 2021
     
          
      - layout: left
        border: weak
        title: 兴隆希尔顿逸林酒店
        sub_title: IT经理 | 296 Rooms
        caption: January 2018 - February 2020 
        description: |
          IT部： 

            - 参与并领导开业前的IT硬件设备和系统采购工作，确保设备和系统符合集团的实施标准和运营需求。
            - 负责编制IT资本预算、政策与流程、培训计划，并与IT团队共享服务。
            - 具有处理运营系统和ELV系统评估与实施、WAN建设和维护、酒店信息化项目批准的经验。
            - 负责日常IT运营管理，例如月度报告、更新酒店和集团所需的各种数据、沟通等。
            - 指导和发展IT团队。
            - 监督计算机技能和业务系统培训与发展，确保每月的培训得以适当进行并与公司文化相匹配。

          前厅部：

            前厅副经理 - 负责礼宾部及及康体中心运营

            
      - layout: left
        border: weak
        title: 美兰机场逸唐飞行酒店
        sub_title: IT部门负责人 | 996 Rooms
        caption: September 2016 - January 2018
        description: |
          
      - layout: left
        border: weak
        title: 海口鲁能希尔顿酒店
        sub_title: IT主管 ｜ 442 rooms
        caption: September 2016 - October 2016
        description: |
         

  - title: 教育
    layout: list
    content:
      - title: 海南职业技术学院
        sub_title: 计算机网络技术专业
        caption: 2004 - 2007
        description: |
          During my degree at Bristol University I learnt lots of key skills such as team work and project management. Although
          we mainly focused on software development and the principles of programming I use a lot of these skills to
          my advantage in my day to day work.

          While at Bristol Uni I spent a lot of my free time with the Kitesurfing society. I spent 3 years on the committee
          as a secretary, trip rep and then media and promotions manager. During this time I took on roles from organising
          transport and designing posters to organising a trip to Portugal for over 30 students.

  - title: When I'm Not Programming
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I'm not sat at my desk I am very active and spend most of my time outdoors. I do a lot a sports such as
      mountain biking, road cycling, kitesuring and horse riding as well as trying to make time for things like
      rock climbing and playing some rugby. I currently have 2 horses and find this is a great way to get out of the house
      and taking my mind of things while learing to showjump.

      I'm interested in photography and videography as I like to be creative, this is mainly through sport but
      I enjoy landscape and abstract photography too. I like to showcase my work on instagram if
      you would like to take a look - [jameswgrant](https://www.instagram.com/jameswgrant/).

      Finally during the rest of my free time you will either find me working on my bikes, rock climbing at one of
      Bristol's indoor climbing centres or down 'The Rec' supporting Bath Rugby.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed
